# Generated by Django 5.0.6 on 2024-05-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_messageing_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageing',
            old_name='read',
            new_name='is_read',
        ),
    ]
