# Generated by Django 5.0.6 on 2024-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_rename_read_messageing_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories'), ('xl', 'XL')], default='men', max_length=20),
        ),
    ]
