# Generated by Django 5.0.6 on 2024-05-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories')], default='men', max_length=20),
        ),
    ]
